In [2]:
import data_gen
import main_simulation
import visualizations

from importlib import reload

reload(data_gen)
reload(main_simulation)
reload(visualizations)

from data_gen import *
from main_simulation import *
from visualizations import *

In [3]:
def simulate_combination(player_1_seq, player_2_seq, decks) -> "arrays":

        #creating a dictionary recording wins 
        wins_dict = {
        'player_1_seq':str(player_1_seq),
        'player_2_seq':str(player_2_seq),
        'player_1_wins_cards':0,
        'ties_cards':0,
        'player_1_wins_tricks':0,
        'ties_tricks':0
        }

        #if players are the same sequence, make results null
        if player_1_seq == player_2_seq:
            wins_dict = {
            'player_1_seq':str(player_1_seq),
            'player_2_seq':str(player_2_seq),
            'player_1_wins_cards':None,
            'ties_cards':None,
            'player_1_wins_tricks':None,
            'ties_tricks':None
            }

        #play the game on each deck and save when player 1 wins
        for deck in decks:
            game_dict = play_game(deck, player_1_seq = player_1_seq, player_2_seq = player_2_seq)

            if game_dict['winner_cards'] == 'player_1':
                wins_dict['player_1_wins_cards'] += 1

            elif game_dict['winner_cards'] == 'tie':
                wins_dict['ties_cards'] += 1  

            if game_dict['winner_tricks'] == 'player_1':
                wins_dict['player_1_wins_tricks'] += 1

            elif game_dict['winner_tricks'] == 'tie':
                wins_dict['ties_tricks'] += 1 

        #convert that to a DF
        wins_dict_df = pd.DataFrame(wins_dict, index = [0])
        
        return wins_dict_df

In [16]:
def simulate_games(decks, combinations = COMBINATIONS) -> "dataframe":
    #creating an empty dataframe of results
    results = pd.DataFrame(columns = ('player_1_seq',
                                    'player_2_seq',
                                    'player_1_wins_cards', 
                                    'ties_cards', 
                                    'player_1_wins_tricks',
                                    'ties_tricks'))
    all_wins = {}
    
    #simulate games for each combination
    for (player_1_seq, player_2_seq) in combinations:
        
        wins = simulate_combination(player_1_seq, player_2_seq, decks)
        results = pd.concat([results, wins])
        
        all_wins[(player_1_seq, player_2_seq)] = wins
                           
    n_games = len(decks)
                           
    return results, n_games, all_wins

In [8]:
def process_results(results, n_games):
    
    #reshape card results to be an array
    results_cards = results[['player_1_seq', 'player_2_seq', 'player_1_wins_cards']]

    results_cards_matrix = pd.pivot_table(results_cards, values = 'player_1_wins_cards', index = 'player_1_seq', 
                                     columns = 'player_2_seq').astype(float)
    
    ties_cards = results[['player_1_seq', 'player_2_seq', 'ties_cards']]

    ties_cards_matrix = pd.pivot_table(ties_cards, values = 'ties_cards', index = 'player_1_seq', 
                                     columns = 'player_2_seq').astype(float)
       
    #reshape card results to be an array
    results_tricks = results[['player_1_seq', 'player_2_seq', 'player_1_wins_tricks']]

    results_tricks_matrix = pd.pivot_table(results_tricks, values = 'player_1_wins_tricks', index = 'player_1_seq', 
                                     columns = 'player_2_seq').astype(float)
    
    ties_tricks = results[['player_1_seq', 'player_2_seq', 'ties_tricks']]

    ties_tricks_matrix = pd.pivot_table(ties_tricks, values = 'ties_tricks', index = 'player_1_seq', 
                                     columns = 'player_2_seq').astype(float)
    
    #calculate win rate pct instead of total
    results_cards_rate = results_cards_matrix/n_games* 100
    results_tricks_rate = results_tricks_matrix/n_games* 100
    ties_cards_rate = ties_cards_matrix/n_games * 100
    ties_tricks_rate = ties_tricks_matrix/n_games * 100
    
   

    return results_cards_rate, results_tricks_rate, ties_cards_rate, ties_tricks_rate

In [9]:
#Or you can use these pre-generated decks
deck_loc = 'data/decks_20250228010552.npy'

In [10]:
decks = np.load(deck_loc)

In [12]:
results, n_decks = simulate_games(decks)

In [14]:
results_cards_rate, results_tricks_rate, ties_cards_rate, ties_tricks_rate = process_results(results, n_decks)

In [15]:
results_cards_rate

player_2_seq,"[0, 0, 0]","[0, 0, 1]","[0, 1, 0]","[0, 1, 1]","[1, 0, 0]","[1, 0, 1]","[1, 1, 0]","[1, 1, 1]"
player_1_seq,,,,,,,,
"[0, 0, 0]",NaN,47.203,27.989,19.006,0.008,26.036,1.521,48.757
"[0, 0, 1]",50.591,NaN,85.227,93.649,0.363,89.063,47.520,98.047
"[0, 1, 0]",70.159,13.009,NaN,48.024,42.236,48.826,9.144,71.299
"[0, 1, 1]",78.408,5.110,48.267,NaN,48.374,55.092,99.588,99.995
"[1, 0, 0]",99.992,99.631,54.951,48.129,NaN,48.430,5.149,78.529
"[1, 0, 1]",71.307,9.120,48.684,42.165,48.085,NaN,13.262,70.073
"[1, 1, 0]",97.922,47.400,89.010,0.356,93.568,85.110,NaN,50.561
"[1, 1, 1]",48.346,1.397,25.925,0.003,18.717,28.055,47.005,NaN

In [ ]:
def add_decks ()